# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, async, fgl, hspec, stm, transformers }:

cabal.mkDerivation (self: {
  pname = "taskpool";
  version = "0.0.3";
  src = builtins.filterSource (path: type: type != "unknown") ./.;
  buildDepends = [ async fgl stm transformers ];
  testDepends = [ hspec ];
  meta = {
    description = "STM/async framework for pools of possibly inter-dependent tasks";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
