# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, async, fgl, hspec, stm, time, transformers }:

cabal.mkDerivation (self: {
  pname = "async-pool";
  version = "0.1.0";
  src = builtins.filterSource (path: type: type != "unknown") ./.;
  buildDepends = [ async fgl stm transformers ];
  testDepends = [ async fgl hspec stm time transformers ];
  meta = {
    description = "Manage pools of possibly interdependent tasks using STM and async";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
